### ISSUE TITLE
There is no difference between Armed Away and Armed Home

### ISSUE THREAD

**Issue by PRoomberg** [bschollnick/Indigo-Switchboard#2]
The Armed state makes no difference between Away and Home.
But both states can have different actions that need to be performed.

**Comment by bschollnick** [comment]
I'll have to take a look at the code.  It's been a while since I looked at switchboard, but I suspect that Home vs Away indeed have no difference.  

There was a plan to eventually make switchboard have a "Security" alarm style mode, where Away vs Home would have a significant difference (eg fire off Sirens, etc).  

I'm open to any suggestions on implementation details...

**Comment by PRoomberg** [comment]
I’ve added a change to the plugin so it recognizes Armed Home.
